=head1 NAME
 
RapidApp::Manual::Installation - Installing RapidApp on a new system
 
=head1 Install from CPAN
 
RapidApp is a standard CPAN package and can be installed in the standard manner:

  cpanm RapidApp

RapidApp does have a lot of dependencies so be prepared for this to take a while. 

If you are new to perl and you don't have C<cpanm> (or know what it is) is, or if 
you would like to play with RapidApp without messing with your main system perl, 
see the next section for installation with perlbrew.

=head1 Installation via Perlbrew

The following is the typical series of commands to run to install a fresh version
of perl into your home directory using perlbrew. This isn't specific to RapidApp,
but perl in general. See L<http://perlbrew.pl> for more info on the perlbrew project.

Run the following commands on any Unix system (including Linux and Mac) to 
install a fresh perlbrew and RapidApp:

  wget -O - http://install.perlbrew.pl | bash

Assuming the above worked, it should tell you to run this:

  source ~/perl5/perlbrew/etc/bashrc

Now you have the C<perlbrew> command and you can install a version of perl. To see
the available versions, you can run C<perlbrew available>. Choose one from the list and 
install it. For example:

  perlbrew install perl-5.20.1

The above command may take a while. Once it completes, make it the active C<perl> and 
install C<cpanm>

  perlbrew switch perl-5.20.1
  perlbrew install-cpanm

Now both C<perl> and C<cpanm> should point to the new perlbrew version within your 
shell (as long as you source their bashrc file). To remember this for your account
for next time, do something like the following:

  echo -e "\nsource ~/perl5/perlbrew/etc/bashrc" >> ~/.bash_profile

Now you can install RapidApp:

  cpanm RapidApp

=head2 Alternative one-line install

The above list of steps can be performed all at once using the C<instant-perlbrew> script
which is available on GitHub. If you are feeling brave, you can paste this one-liner to install
perlbrew+RapidApp on most Unix-based systems in one swoop:

  time wget -O - \
   https://raw.githubusercontent.com/vanstyn/instant-perlbrew/v1/instant-perlbrew.sh \
   | bash -s perl-5.20.1 RapidApp

This can take in the neighborhood of an hour, depending on the speed of your system.
See L<github.com/vanstyn/instant-perlbrew|https://github.com/vanstyn/instant-perlbrew> for 
more information on the C<instant-perlbrew.pl> script and exactly what it does.

=head1 SEE ALSO

=over

=item *

L<RapidApp::Manual>

=item *

L<RapidApp::Manual::Bootstrap>

=back

=cut
