=head1 NAME
 
RapidApp::Manual::RapidDbic - Using the RapidDbic plugin
 
=head1 DESCRIPTION

"RapidDbic" is the main RapidApp plugin which provides an abstract configuration layer for a common, 
simplified declarative API for accessing many of the DBIC-enabled modules and features available
in the RapidApp distribution quickly and easily. This is provided in the form of a fully-working, 
self-assembled CRUD-style admin application.

RapidDbic also provides a common app structure which acts like a hub through which other high-level 
plugins can attach to activate other instant features, like users and permissions. 

RapidDbic can also be used to attach admin sections to existing Catalyst applications with relative
ease.

Instantly generated RapidDbic CRUD applications can also be initialized and mounted as a 
L<Plack>-compatable app with L<Plack::App::RapidApp::rDbic>. There is also the command-line wrapper 
script L<rdbic.pl> which can be used to launch a working app for any existing database via dsn in 
a single shell command:

  rdbic.pl dbi:mysql:mydb

To learn more, see the L<Catalyst::Plugin::RapidApp::RapidDbic> documentation itself. Also, the 
examples in L<RapidApp::Manual::Bootstrap> mainly cover RapidDbic, which show how to bootstrap a new 
app from scratch, also with a single command, which can then be further customized and developed.

Additionally, the Chinook Demo video series on the RapidApp website covers building an app using 
RapidDbic extensively:

=over

=item *

L<Chinook Demo (www.rapidapp.info/demos/chinook)|http://www.rapidapp.info/demos/chinook>

=back

=head1 SEE ALSO

=over

=item *

L<Catalyst::Plugin::RapidApp::RapidDbic>

=item *

L<Plack::App::RapidApp::rDbic>

=item *

L<rdbic.pl>

=item *

L<RapidApp::Manual>

=item *

L<RapidApp::Manual::TableSpec>

=item *

L<RapidApp::Manual::Bootstrap>

=item * 

L<Catalyst>

=back
 
=cut
