=head1 NAME
 
RapidApp::Manual - Index of the Manual
 
=head1 DESCRIPTION
 
This is the L<RapidApp> users manual, which is still in progress. RapidApp is 
a new open-source web application framework based on L<Catalyst>, ExtJS, 
L<Template::Toolkit> and L<DBIx::Class> for quickly creating interactive, 
data-rich webapps.

For more information see the RapidApp home page at L<http://www.rapidapp.info>.
 
=head1 SECTIONS
 
=head2 L<RapidApp::Manual::RapidDbic>
 
Usage and config options for the RapidDbic plugin.
 
=head2 L<RapidApp::Manual::TableSpec>
 
Listing of 'TableSpec' config options. TableSpecs are additional,
RapidApp-specific metadata associated with DBIx::Class result classes.
 
=head2 L<RapidApp::Manual::Assets>
 
Built-in functionality for managing and serving "Assets" (CSS, JavaScript, 
Images, etc)

=cut
